apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: Up-and-Running-with-Docker-Express
spec:
  selector:
    name: web
    type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  