apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        image: hello
        name : web
        ports:
        - containerPort: 3000