apiVersion: v1
kind: Pod
metadata:
  name: helloWorldExample
  labels:
    app: helloWorld

spec:
  containers:
  - image: alishagupta/hello
    name : Demo
    ports:
    - containerPort: 30004
  imagePullSecrets:
    -name: regcred
    